
services:
  xiidea.easy_audit.doctrine_subscriber:
          class: Xiidea\EasyAuditBundle\Subscriber\DoctrineSubscriber
          arguments: ['%xiidea.easy_audit.doctrine_entities%']
          calls:
              - [ setDispatcher,[ '@event_dispatcher' ] ]
              - [ setAnnotationReader,[ '@annotation_reader' ] ]
          tags:
              - { name: doctrine.event_subscriber }
